package main

import (
	_ "github.com/ernestokarim/cb/tasks/aliases/v0"
	_ "github.com/ernestokarim/cb/tasks/angular/v0"
	_ "github.com/ernestokarim/cb/tasks/cacherev/v0"
	_ "github.com/ernestokarim/cb/tasks/cbtest/v0"
	_ "github.com/ernestokarim/cb/tasks/clean/v0"
	_ "github.com/ernestokarim/cb/tasks/closurejs/v0"
	_ "github.com/ernestokarim/cb/tasks/compilejs/v0"
	_ "github.com/ernestokarim/cb/tasks/concat/v0"
	_ "github.com/ernestokarim/cb/tasks/dist/v0"
	_ "github.com/ernestokarim/cb/tasks/htmlmin/v0"
	_ "github.com/ernestokarim/cb/tasks/imagemin/v0"
	_ "github.com/ernestokarim/cb/tasks/init/v0"
	_ "github.com/ernestokarim/cb/tasks/lint/v0"
	_ "github.com/ernestokarim/cb/tasks/minignore/v0"
	_ "github.com/ernestokarim/cb/tasks/ngmin/v0"
	_ "github.com/ernestokarim/cb/tasks/recess/v0"
	_ "github.com/ernestokarim/cb/tasks/sass/v0"
	_ "github.com/ernestokarim/cb/tasks/server/v0"
	_ "github.com/ernestokarim/cb/tasks/soy/v0"
	_ "github.com/ernestokarim/cb/tasks/test/v0"
	_ "github.com/ernestokarim/cb/tasks/watch/v0"
)
