
# Application info
application: {{.AppName}}
version: beta
runtime: go
api_version: go1

# Switch on the remote api and the datastore admin tool
builtins:
- remote_api: on
- datastore_admin: on

handlers:
# Static files
- url: /components/(.*)
  static_files: static/components/\1
  upload: static/components/(.*)
  expiration: "20d"

- url: /fonts/(.*)
  static_files: static/fonts/\1
  upload: static/fonts/(.*)
  expiration: "20d"

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)
  expiration: "20d"

- url: /scripts/(.*)
  static_files: static/scripts/\1
  upload: static/scripts/(.*)
  expiration: "20d"

- url: /styles/(.*)
  static_files: static/styles/\1
  upload: static/styles/(.*)
  expiration: "20d"

# Commented out because the templates are compiled
# to the JS file. Uncomment if needed.
# - url: /views/(.*)
#   static_files: static/views/\1
#   upload: static/views/(.*)
#   expiration: "20s"

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "20d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "20d"

# Special urls, for tasks and cron
- url: /tasks/.*
  script: _go_app
  login: admin

- url: /cron/.*
  script: _go_app
  login: admin

# The rest of the app
- url: /.*
  script: _go_app


env_variables:
  # Fixes a datastore problem in the devserver in Windows
  TMP: C:\Users\PHOENIX\AppData\Local\Temp


# Avoid upload some backup and unused files
skip_files:
- old
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*/build/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.md$
- ^(.*/)?datastore
- ^(.*/)?Thumbs\.db$
- ^(.*/)?.*_test\.go$
- ^(.*/)?.*_example\.go$
- ^(.*/)?.*/example/.*
- ^(.*/)?.*/out/.*
- ^(.*/)?.*/examples/.*
- ^(.*/)?.*/tools/.*
- ^(.*/)?.*/old/.*
- ^(.*/)?.*/build/.*
- ^(.*/)?.*/client/.*
