package templates

func init() {
	mode := "bootstrap3"

	registerTemplate(mode, "form", `
<!-- AUTOGENERATED BY cb FROM {{ .FileName }}, PLEASE, DON'T MODIFY IT -->
<form class="form-horizontal" name="{{ .Name }}" novalidate ng-init="{{ .Name }}.val = false;"
    ng-submit="{{ .Name }}.val = true; {{ .TrySubmit }}(); {{ .Name }}.$setPristine(); {{ .Name }}.$valid && {{.Submit }}()"><fieldset>{{ .Content }}</fieldset></form>`)
	registerTemplate(mode, "field", `
  <div class="form-group"{{ if .Messages }} ng-class="{{ .Name }}.val && ({{ .Name }}{{ .FieldId }}.$invalid{{ .ShowErrors }}) && 'has-error'"{{ end }}{{ .ContainerAttrs }}>{{ if .Label }}
    <label for="{{ .Name }}{{ .Id }}" class="control-label {{ .LabelSize }}">{{ .Label }}</label>{{ end }}
    <div class="{{ .Size }}">
      %s
    </div>
    <div class="clearfix">&nbsp;</div>
    {{ .Messages }}
  </div>
  `)
	registerTemplate(mode, "error-messages", `
    <p class="help-block {{ .Size }}" ng-show="{{ .Name }}.val && ({{ .Name }}{{ .Id }}.$invalid{{ .ShowErrors }})">
{{ .Errors }}    </p>
  `)
	registerTemplate(mode, "checkbox-field", `
  <div class="form-group">
    <div class="col-sm-offset-3 col-lg-offset-2 col-md-9 col-lg-10">
      <div class="checkbox">
        <label>
          {{ .Ctrl }}
          {{ .Name }}
        </label>
      </div>
    </div>
  </div>
  `)
}
