package v0

func init() {
	mode := "detail"

	registerTemplate(mode, "form", `
<!-- AUTOGENERATED BY cb FROM {{ .FileName }}, PLEASE, DON'T MODIFY IT -->
<form class="inline-input" name="{{ .Name }}" novalidate ng-init="{{ .Name }}.val = false;"
    ng-submit="{{ .Name }}.$valid && {{.SubmitFunc }}()"><fieldset>{{ .Content }}</fieldset></form>
  `)
	registerTemplate(mode, "submit-field", `
  <div class="row">
    <div class="col-md-12 actions">
      <button ng-click="{{ .TrySubmitFunc }}(); {{ .Name }}.val = true;" class="btn-flat primary"
        ng-disabled="{{ .Name }}.val && !{{ .Name }}.$valid">{{ .Label }}</button>{{ .Cancel }}
    </div>
  </div>
  `)

	fieldTemplate := `
  <div class="row">
    <div class="col-md-12 field-box" ng-class="{{ .Name }}.val && {{ .Errs }} && 'error'">
      <label for="{{ .Name }}{{ .Id }}">{{ .Label }}</label>
      %s{{ .Messages }}
    </div>
  </div>
  `
	registerTemplate(mode, "field", fieldTemplate)
	registerTemplate(mode, "field-nolabel", fieldTemplate)
	registerTemplate(mode, "error-messages", `
    <p class="form-errors" ng-show="{{ .Name }}.val && ({{ .Name }}{{ .Id }}.$invalid{{ .ShowErrors }})">
      {{ .ValErrors }}
    </p>
  `)
	registerTemplate(mode, "checkbox-field", `
  <div class="row"><div class="col-md-12 field-box checkbox-field">
    <label class="checkbox">
      {{ .Ctrl }}
      {{ .Name }}
    </label>
  </div></div>
  `)
}
