package v0

func init() {
	mode := "bootstrap3"

	registerTemplate(mode, "form", `
<!-- AUTOGENERATED BY cb FROM {{ .FileName }}, PLEASE, DON'T MODIFY IT -->
<form class="form-horizontal" name="{{ .Name }}" novalidate ng-init="{{ .Name }}.val = false;"
    ng-submit="{{ .Name }}.$valid && {{.SubmitFunc }}()"><fieldset>{{ .Content }}</fieldset></form>
  `)
	registerTemplate(mode, "submit-field", `
  <div class="form-group">
    <p>&nbsp;</p>
    <div class="col-sm-offset-3 col-md-9 col-lg-offset-2 col-lg-10">
      <button ng-click="{{ .TrySubmitFunc }}(); {{ .Name }}.val = true;" class="btn btn-primary"
        ng-disabled="{{ .Name }}.val && !{{ .Name }}.$valid">{{ .Label }}</button>{{ .Cancel }}
    </div>
  </div>
  `)
	registerTemplate(mode, "field", `
  <div class="form-group" ng-class="{{ .Name }}.val && {{ .Errs }} && 'has-error'">
    <label for="{{ .Name }}{{ .Id }}" class="control-label col-xs-3 col-lg-2">{{ .Label }}</label>
    <div class="col-xs-9 col-lg-10">
      <div class="row">
        <div class="{{ .Size }}">
          %s
        </div>
      </div>{{ .Messages }}
    </div>
  </div>
  `)
	registerTemplate(mode, "field-nolabel", `
  <div class="form-group" ng-class="{{ .Name }}.val && {{ .Errs }} && 'has-error'">
    <div class="col-sm-offset-3 col-lg-offset-2 col-md-9 col-lg-10">
      <div class="row">
        <div class="{{ .Size }}">
          %s
        </div>
      </div>{{ .Messages }}
    </div>
  </div>
  `)
	registerTemplate(mode, "error-messages", `
      <p class="help-block" ng-show="{{ .Name }}.val && ({{ .Name }}{{ .Id }}.$invalid{{ .ShowErrors }})">
{{ .ValErrors }}      </p>
  `)
	registerTemplate(mode, "checkbox-field", `
  <div class="form-group">
    <div class="col-sm-offset-3 col-lg-offset-2 col-md-9 col-lg-10">
      <div class="checkbox">
        <label>
          {{ .Ctrl }}
          {{ .Name }}
        </label>
      </div>
    </div>
  </div>
  `)
}
