package v0

func init() {
	mode := "bootstrap"

	registerTemplate(mode, "form", `
<!-- AUTOGENERATED BY cb FROM {{ .FileName }}, PLEASE, DON'T MODIFY IT -->
<form class="form-horizontal" name="{{ .Name }}" novalidate ng-init="{{ .Name }}.val = false;"
    ng-submit="{{ .Name }}.$valid && {{.SubmitFunc }}()"><fieldset>{{ .Content }}</fieldset></form>
  `)
	registerTemplate(mode, "submit-field", `
  <div class="form-actions">
    <button ng-click="{{ .TrySubmitFunc }}(); {{ .Name }}.val = true;" class="btn btn-primary"
      ng-disabled="{{ .Name }}.val && !{{ .Name }}.$valid">{{ .Label }}</button>{{ .Cancel }}
  </div>
  `)
	registerTemplate(mode, "field", `
  <div class="control-group" ng-class="{{ .Name }}.val && {{ .Errs }} && 'error'">
    <label class="control-label" for="{{ .Name }}{{ .Id }}">{{ .Label }}</label>
    <div class="controls">
      %s{{ .Messages }}
    </div>
  </div>
  `)
	registerTemplate(mode, "field-nolabel", `
  <div class="control-group" ng-class="{{ .Name }}.val && {{ .Errs }} && 'error'">
    %s{{ .Messages }}
  </div>
  `)
}
