
{{ if .ClientOnly }}clientonly: true
{{end}}base: base.html{{ if not .ClientOnly }}
deploy: gae{{end}}

recess:
  - source: bootstrap/main.less
    dest:   bootstrap.css

sass:
  - source: app.scss
    dest:   app.css

watch:
  - task: recess
    paths:
      - app/components/bootstrap/less/*.less
      - app/styles/bootstrap/*.less
      - app/styles/font-awesome/*.less

  - task: sass
    paths:
      - app/styles/**/*.scss

cacherev:
  dirs:
    - images
    - styles
    - scripts
    - fonts
    - components
  rev:
    - styles
    - views
    - base.html

htmlmin:
  - source: app/views
    dest: temp/views
  - source: temp/base.html
    dest: temp/base.html

prepare_dist:
  - app

dist:
  - base.html
  - components/jquery/jquery.min.js
  - favicon.ico
  - fonts
  - images
  - robots.txt
  - scripts/ie.js
  - scripts/test.js
  - scripts/{{ .AppName }}.js
  - styles/{{ .AppName }}.css

ngtemplates:
  appendto: scripts/{{ .AppName }}.js
  files:
    - views/**
